runtime: python39
entrypoint: gunicorn -b :8080 Deploy_Newsapp:app  # Crucial change!
instance_class: F2
env_variables:
  OPENAI_API_KEY: "your-api-key"
  DATABASE_URL: "your-database-url"
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto